#define HAVE_SYSCONF 1
#define HAVE_SCHED_GETCPU 1
#define HAVE_SCHED_SETAFFINITY 1
#define CONFIG_RCU_HAVE_FUTEX 1	
#define CONFIG_RCU_SMP 1
#define CONFIG_RCU_HAVE_FENCE 1
#define CONFIG_RCU_COMPAT_ARCH 1
